# This workflow ONLY deploys a pre-generated report folder.
# It does NOT run any tests.
name: Deploy Pre-generated Playwright Report

on:
    workflow_dispatch:
    push:
        branches: [main]

jobs:
    test-and-deploy:
        runs-on: ubuntu-latest
        
        # ADDED: Forces the current actions to use Node 24 to fix the warning
        env:
            FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

        permissions:
            pages: write 
            id-token: write 

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 18 

            - name: Install dependencies
              run: npm install

            - name: Install Playwright Browsers
              run: npx playwright install --with-deps

            - name: Run Playwright tests
              run: npx playwright test
              env:
                  BASE_URL: ${{secrets.BASE_URL}}
                  LOGIN_USERNAME: ${{secrets.LOGIN_USERNAME}}
                  LOGIN_PASSWORD: ${{secrets.LOGIN_PASSWORD}}
                  COMPANY_NAME: ${{secrets.COMPANY_NAME}}
              continue-on-error: true

            - name: Install Allure Commandline
              run: npm install -g allure-commandline

            - name: Generate Allure Report
              run: allure generate allure-results --clean -o allure-report

            - name: Upload test report artifact
              uses: actions/upload-pages-artifact@v3
              with:
                  path: allure-report/
                  retention-days: 30

            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
